language: 
    java

sudo: required

services:
- docker

install:
    sudo apt-get install python3-dev
 
script:
- mvn package
- docker build . -t blz:ci-$(echo $TRAVIS_BRANCH)-$(echo $TRAVIS_BUILD_NUMBER)
- cd Tests/
- python3 runtests.py
